"""Celery worker + beat schedule for the workflow service.

A Celery app on the shared Redis broker (VE_REDIS_URL) that drives the workflow
engine's scheduled + async work. Each Celery task below wraps one async body via
``asyncio.run``; the bodies live in the ``jobs`` module of the feature that OWNS
the work, not in a shared task module. Three imports instead of one is the point:
it says on the import line which part of the domain each sweep belongs to.

Tasks:
  * ``escalation_sweep``       — SLA breach + state-timeout + SOP-rule escalations.
  * ``timeout_sweep``          — auto-cancel stale instances.
  * ``dispatch_notifications`` — drain the notification outbox via connectors.
  * ``run_correlation_consumer`` — the NATS→incident engine (long-running; start it
    once, e.g. ``celery -A app.worker call app.worker.run_correlation_consumer``,
    or run it as a dedicated process alongside the worker).

Beat schedule runs the three sweeps periodically. The correlation consumer is a
blocking long-runner and is NOT on the beat schedule (it would never return).

HEALTH. Neither process has a web framework and neither should grow one, but a
Celery worker that has stopped consuming has NO outward symptom -- the process is
up, the broker connection is established, the logs are quiet and
``celery inspect ping`` answers pong, because ping is served by the control
consumer on a broadcast queue rather than by the one carrying tasks. So both
processes start a ~40-line stdlib probe server on :8000 (they are separate
containers, so neither collides with the API's) and stamp a heartbeat from a
Celery signal:

  * the WORKER stamps ``task_postrun`` -- a task ran to completion. The beat
    schedule below publishes two sweeps every minute forever, so this heartbeat is
    generated by the system's own clockwork and NOT by operator traffic: an estate
    with no incidents at all still produces it, which is the only way a liveness
    flag on an idle queue survives contact with an operator.
  * BEAT stamps ``before_task_publish`` -- a task was sent. Read together they name
    the right container: beat fresh + worker silent is a wedged worker; both
    silent is a dead beat or a dead broker.

See app/probes.py and app/workflow/runtime/heartbeat.py for the windows and why.

Run the worker:  celery -A app.worker.celery_app worker --loglevel=info
Run beat:        celery -A app.worker.celery_app beat --loglevel=info
"""

from __future__ import annotations

import asyncio
import logging
import os

from celery import Celery
from celery.schedules import crontab
from celery.signals import beat_init, before_task_publish, task_postrun, worker_ready

from kernel.config import get_settings

from app import logs
from app.probes import ProcessProbeServer
from app.workflow.correlation import jobs as correlation_jobs
from app.workflow.instances import jobs as instance_jobs
from app.workflow.notifications import jobs as notification_jobs
from app.workflow.runtime import heartbeat

log = logging.getLogger("workflow.worker")

PROBE_PORT = int(os.getenv("VE_WORKFLOW_PROBE_PORT", "8000"))

settings = get_settings()

celery_app = Celery(
    "workflow",
    broker=settings.redis_url,
    backend=settings.redis_url,
    include=["app.worker"],
)

celery_app.conf.update(
    task_serializer="json",
    accept_content=["json"],
    result_serializer="json",
    timezone="UTC",
    enable_utc=True,
)

# --- beat schedule ---------------------------------------------------------
celery_app.conf.beat_schedule = {
    "workflow-escalation-sweep": {
        "task": "app.worker.escalation_sweep",
        "schedule": crontab(minute="*"),  # every minute
    },
    "workflow-timeout-sweep": {
        "task": "app.worker.timeout_sweep",
        "schedule": crontab(minute="*/5"),  # every 5 minutes
    },
    "workflow-dispatch-notifications": {
        "task": "app.worker.dispatch_notifications",
        "schedule": crontab(minute="*"),  # every minute
    },
    "workflow-dedup-cleanup": {
        "task": "app.worker.dedup_cleanup",
        "schedule": crontab(minute="*/10"),  # every 10 minutes
    },
}


# --- health signals --------------------------------------------------------
#
# One module, two processes: `celery worker` fires worker_ready/task_postrun and
# `celery beat` fires beat_init/before_task_publish, so each process arms only the
# half that belongs to it and neither needs to be told which one it is.

_probe: ProcessProbeServer | None = None
_role: str | None = None


def _arm(role: str, silence: float) -> None:
    """Start this process's probe server and reset its heartbeat. MainProcess only."""
    global _probe, _role
    if _probe is not None:
        return
    try:
        logs.configure(role)
        _role = role
        heartbeat.arm(role)
        _probe = ProcessProbeServer(role, port=PROBE_PORT, silence_limit=silence)
        _probe.start()
    except Exception as e:  # noqa: BLE001
        # A probe that cannot start must not stop the worker from working. It
        # fails LOUDLY and stays absent, which the container healthcheck then
        # reports as unhealthy -- the correct outcome, and the opposite of a
        # silent one.
        log.exception("probe server failed to start for role=%s: %s", role, e)


@worker_ready.connect
def _worker_ready(**_kw) -> None:
    _arm("worker", heartbeat.WORKER_SILENCE_SEC)


@beat_init.connect
def _beat_ready(**_kw) -> None:
    _arm("beat", heartbeat.BEAT_SILENCE_SEC)


@task_postrun.connect
def _note_task(task=None, state=None, **_kw) -> None:
    """A task ran to completion. THE worker liveness signal.

    Fires in a FORKED CHILD under the default prefork pool, which is why the
    counters live in Redis and not in this module: an in-process counter here is
    invisible to the probe thread in MainProcess and separately wrong in each of
    the eleven children. The role is spelled literally for the same reason:
    `_role` is set in the parent at worker_ready, which is AFTER the fork, so a
    child would read None. Only a worker runs task bodies, so there is nothing to
    branch on.

    task_postrun and not task_success, because a task that FAILED still proves the
    whole chain being watched: broker reachable, queue consumed, pool alive, body
    executed. Counting only successes would make a service whose SMTP server is
    down look like a service whose worker is dead, and those need opposite
    responses. Failures are counted separately for exactly that reason.
    """
    name = getattr(task, "name", "?")
    heartbeat.note("worker", name, failed=(state == "FAILURE"))


@before_task_publish.connect
def _note_publish(sender=None, **_kw) -> None:
    """A task was SENT. Beat's liveness signal.

    Guarded on the role because this signal also fires in any process that calls
    `.delay()`; only beat is on a schedule, and a worker chaining a task must not
    be able to make a dead beat look alive.
    """
    if _role != "beat":
        return
    heartbeat.note("beat", str(sender))


# --- tasks -----------------------------------------------------------------


@celery_app.task(name="app.worker.escalation_sweep")
def escalation_sweep() -> int:
    """SLA breach + state-timeout + SOP escalation-rule sweep."""
    return asyncio.run(instance_jobs.escalation_sweep())


@celery_app.task(name="app.worker.timeout_sweep")
def timeout_sweep() -> int:
    """Auto-cancel instances idle past the global timeout."""
    return asyncio.run(instance_jobs.timeout_sweep())


@celery_app.task(name="app.worker.dispatch_notifications")
def dispatch_notifications() -> int:
    """Drain the notification outbox through the connector registry."""
    return asyncio.run(notification_jobs.dispatch_notifications())


@celery_app.task(name="app.worker.dedup_cleanup")
def dedup_cleanup() -> int:
    """Delete expired correlation-dedup slots."""
    return asyncio.run(correlation_jobs.dedup_cleanup())


@celery_app.task(name="app.worker.run_correlation_consumer")
def run_correlation_consumer() -> str:
    """Long-running NATS→incident consumer. Blocks; run as a dedicated worker."""
    asyncio.run(correlation_jobs.run_correlation_consumer())
    return "stopped"


@celery_app.task(name="app.worker.run_notify_consumer")
def run_notify_consumer() -> str:
    """Long-running NATS notify.request/vms.popup → outbox consumer. Blocks."""
    asyncio.run(notification_jobs.run_notify_consumer())
    return "stopped"


@celery_app.task(name="app.worker.ping")
def ping() -> str:
    """Sample on-demand task — proves the worker executes queued jobs."""
    return "pong"
