"use client";

// Offline icon registry.
//
// `@iconify/react` normally resolves <Icon icon="heroicons-outline:camera" /> by
// calling api.iconify.design at runtime. This console ships to air-gapped sites,
// so every icon would render blank there — silently, because Iconify treats a
// name it cannot resolve as "not ready yet", forever. Importing this module
// (once, from Providers) registers a bundle of exactly the icons the app uses,
// generated by scripts/build-icon-bundle.mjs, and Iconify then serves them from
// memory.
//
// WHY A SCANNED SUBSET AND NOT WHOLE COLLECTIONS. The predecessor of this file
// registered the four complete sets — 2,106 icons, 954 KB raw / 194 KB gzip on
// every route — arguing that some call sites build an icon name at RUNTIME
// (`iconForType(device.device_type)`, the map pin builder), so a build-time scan
// of literals would miss them. That was checked name by name, and it does not
// hold: every one of those "runtime" names is a lookup in a table whose VALUES
// are string literals (IOT_CATEGORY_ICON, CATEGORIES, BLOCK_LABELS, the access
// constants…), which the scanner sees like any other literal; and the map pin
// builder emits raw SVG, not an Iconify name at all. `npm run icons:check` is
// the standing proof — it fails if any literal in src/ is absent from the bundle.
//
// The one genuinely unscannable name is an alert format's `icon`, which an
// operator types free-hand (workflow config → Alert formats). No bundle can
// cover arbitrary input — whole collections did not either, since a typo or an
// `mdi:` name was blank even then — so that field resolves through
// `bundledIcon()` below, which substitutes a visible glyph instead of nothing.
//
// Adding a new icon to the UI? Run `npm run icons` and commit the result.
import { addAPIProvider, addCollection } from "@iconify/react";
import type { IconifyJSON } from "@iconify/types";

import bundle from "./icon-bundle.json";

// The bundle is written as IconifyJSON[] by scripts/build-icon-bundle.mjs.
// resolveJsonModule instead infers one literal type per collection and folds them
// into a union where every icon absent from a sibling collection becomes
// `?: undefined`, which IconifyIcons' index signature rejects — so the inferred
// type and the real one do not even overlap, hence the cast through unknown.
const collections = bundle as unknown as IconifyJSON[];

for (const collection of collections) {
  addCollection(collection);
}

const BUNDLED = new Set(
  collections.flatMap((c) => [
    ...Object.keys(c.icons ?? {}),
    ...Object.keys(c.aliases ?? {}),
  ].map((name) => `${c.prefix}:${name}`))
);

/**
 * `name` if the bundle can actually draw it, else `fallback`.
 *
 * For icon names that come from OUTSIDE the source tree — today only an alert
 * format's operator-typed `icon` — where an unresolvable name would otherwise
 * render as empty space with no error anywhere. Do not use it for literals: a
 * literal that needs a fallback is a literal `npm run icons` should have picked
 * up, and hiding that behind a substitute glyph is how the blanks accumulated.
 */
export function bundledIcon(name: string | null | undefined, fallback: string): string {
  return name && BUNDLED.has(name) ? name : fallback;
}

// Belt and braces: repoint Iconify's default API provider — which otherwise
// fans out to api.iconify.design, api.simplesvg.com and api.unisvg.com — at our
// own origin. If an icon name ever slips past the bundle it fails fast against a
// local 404 instead of hanging on a DNS lookup that can't succeed offline.
addAPIProvider("", { resources: ["/iconify"], rotate: 200, timeout: 1000 });

// Re-exported so call sites can `import { Icon } from "@/lib/icons"` and get the
// registry set up as a side effect. Existing `@iconify/react` imports keep
// working too — the registry is global.
export { Icon } from "@iconify/react";
