"use client";

// Offline icon registry.
//
// `@iconify/react` normally resolves <Icon icon="heroicons-outline:camera" /> by
// calling api.iconify.design at runtime. This console ships to air-gapped sites,
// so every icon would render blank there. Importing this module (once, from
// Providers) registers a bundle of exactly the icons the app uses, generated by
// scripts/build-icon-bundle.mjs — Iconify then serves them straight from memory
// and never reaches for the network.
//
// Adding a new icon to the UI? Run `npm run icons` (needs network) to refresh
// src/lib/icons/icon-bundle.json, and commit the result.
import { addAPIProvider, addCollection } from "@iconify/react";
import type { IconifyJSON } from "@iconify/types";

import bundle from "./icon-bundle.json";

// The bundle is written as IconifyJSON[] by scripts/build-icon-bundle.mjs.
// resolveJsonModule instead infers one literal type per collection and folds them
// into a union where every icon absent from a sibling collection becomes
// `?: undefined`, which IconifyIcons' index signature rejects — so the inferred
// type and the real one do not even overlap, hence the cast through unknown.
for (const collection of bundle as unknown as IconifyJSON[]) {
  addCollection(collection);
}

// Belt and braces: repoint Iconify's default API provider — which otherwise
// fans out to api.iconify.design, api.simplesvg.com and api.unisvg.com — at our
// own origin. If an icon name ever slips past the bundle it fails fast against a
// local 404 instead of hanging on a DNS lookup that can't succeed offline.
addAPIProvider("", { resources: ["/iconify"], rotate: 200, timeout: 1000 });

// Re-exported so call sites can `import { Icon } from "@/lib/icons"` and get the
// registry set up as a side effect. Existing `@iconify/react` imports keep
// working too — the registry is global.
export { Icon } from "@iconify/react";
