"""reporting: the PROJECTION REGISTRY — how a domain gets into the reporting store

Revision ID: 0005_projection_registry
Revises: 0004_dashboard_datasets
Create Date: 2026-08-30

WHAT WAS MISSING
----------------
`0004_dashboard_datasets` made the dashboard builder domain-agnostic: a dataset
is a row, and a second dataset (`access_events`) was added by one INSERT with no
code change. But that second dataset was a FIXTURE — 2,800 rows generated by
hand into a table nothing wrote. It proved the registry worked and then sat
there going stale, which is how a proof turns into a lie in somebody's
dashboard.

Nothing published. `neubit_reporting` is the one place data from several
services is gathered for querying (builder contract §1) and the platform bans
cross-service reads, so there is exactly one legal way in: a domain PUBLISHES on
the bus and something consumes the bus and writes here. That something is the
**reporting projector** (`backend/projector`), and this revision creates the
table that tells it what to do.

REGISTRATION IS DATA — ALL THE WAY DOWN
---------------------------------------
`dashboard_datasets` already made "what can be charted" data. A projection row
makes "what is collected, and into what" data as well:

    reporting_projections.spec      → the bus subject, the target relation and
                                      its columns, the rollups, the natural key
    reporting_projections.dataset   → the `dashboard_datasets` row to publish
                                      once the relations exist

So a new domain — vision, fire — is ONE INSERT into this table. It needs no
release of the projector, no release of the builder, and no migration: the
projector creates the declared relations, projects the events into them, and
registers the dataset (whose permission the reading-writer then pushes into
core's catalog so a role can grant it).

WHY THE PROJECTOR, NOT THIS MIGRATOR, CREATES THE PROJECTED RELATIONS
---------------------------------------------------------------------
A migration is code and runs at deploy time. A projection is data and can be
inserted at 3am with no deploy. A migration therefore CANNOT know the relations a
projection needs, and if it did, "registration is data" would be false for the
half that matters. So the split is:

    reporting-migrate  owns the IoT schema and THIS table.
    reporting-projector owns every relation declared in THIS table.

The projector's DDL is additive-only and every identifier in a spec is checked
against `^[A-Za-z_][A-Za-z0-9_]*$` before it is quoted — the same allowlist the
SQL generator uses. It creates, it adds columns and indexes, it never drops and
never rewrites a column's type. See `backend/projector/app/ensure.py`.

THE SYNTHETIC FIXTURE GOES
--------------------------
`access_events` (2,800 fabricated rows) and the plain view `access_events_1h`
that stood in for a rollup are dropped here, and the fixture's
`dashboard_datasets` row with them. The projector recreates all three for real:
`access_events` as a hypertable fed by the access service's own domain events,
`access_events_1h` as an actual TimescaleDB continuous aggregate, and the dataset
row from the spec below.

Two columns of the fixture are deliberately NOT recreated, because nothing on the
wire carries them and contract §4 forbids inventing them:

  * `credential_type` — the access service's `AccessEvent` has no such field.
  * `dwell_sec`       — nor a dwell time. The fixture's "Dwell time (s)" measure
                        was a number nobody measured.
"""

from __future__ import annotations

import json

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_projection_registry"
down_revision = "0004_dashboard_datasets"
branch_labels = None
depends_on = None


# ── the access-control projection ────────────────────────────────────────────
#
# The access service already publishes every controller event it ingests onto the
# spine at `tenant.<id>.access.<category>.<event_type>` (see
# `backend/access/app/access/events.py`). It has done so since the service was
# written; nothing was listening for reporting purposes. This spec is that
# listener, expressed as data.
#
# The projector NEVER opens `neubit_access`. Everything below comes out of the
# published envelope, which is why the access service also puts the door's local
# id and name on the wire — the publisher resolves its own dimension, because the
# consumer is not allowed to.

ACCESS_SPEC = {
    "source": {
        # EVENTS, not IOT_READINGS: domain events, low rate, unbounded stream.
        # `tenant.*.access.>` is already in kernel's EVENTS_SUBJECTS, so this
        # subject is captured and a durable consumer can be created on it.
        "stream": "EVENTS",
        # `tenant.*.access.*.*`, NOT `tenant.*.access.>`. The access domain's event
        # taxonomy is `access.<category>.<event_type>` — exactly two tokens — but
        # the service also publishes a one-token lifecycle ping
        # (`tenant.platform.access.startup`, from `access/app/main.py`) that has no
        # event time and can never become a row. Consuming it would mean acking and
        # counting a "malformed message" on every restart of the access service,
        # which is a data-loss counter going up for something that was never data.
        # Do not consume what cannot be projected.
        "subject": "tenant.*.access.*.*",
        "durable": "reporting-projector-access",
    },
    "target": {
        "relation": "access_events",
        "time_column": "ts",
        # Replay on a durable consumer is normal, not exceptional. The natural
        # key is the SOURCE's own event id (the `access_events.id` the access
        # service persisted before publishing) plus the event time — NOT the
        # envelope's `event_id`, which is minted fresh on every publish and would
        # make a redelivery look like a new event.
        "natural_key": ["event_id", "ts"],
        "chunk_interval": "7 days",
        "retention": "1825 days",
        "columns": [
            {"name": "ts", "type": "timestamptz", "source": "payload.occurred_at",
             "required": True},
            # `tenant` means: run it through the tenant resolver, exactly as the
            # reading-writer does. The subject's tenant segment is `platform` for
            # a system row, which is not a uuid and cannot be stored as one.
            {"name": "tenant_id", "type": "uuid", "source": "tenant_id",
             "tenant": True, "required": True},
            {"name": "event_id", "type": "uuid", "source": "payload.event_id",
             "required": True},
            {"name": "instance_id", "type": "text", "source": "payload.instance_id"},
            {"name": "site_id", "type": "text", "source": "payload.site_id"},
            # The LOCAL door: resolved by the access service from its own
            # `access_doors` table before publishing. NULL when the controller
            # reported a door this platform has no local record for — absence
            # renders as absence (contract §4), never as "unknown door".
            {"name": "door_id", "type": "text", "source": "payload.door_id"},
            {"name": "door_name", "type": "text", "source": "payload.door_name"},
            # The controller-side uid. Stored, but not a registered dimension:
            # it is an integration detail, and putting it in the rollup's
            # GROUP BY would double the rollup's cardinality for no chart.
            {"name": "door_ref", "type": "text", "source": "payload.door_ref"},
            {"name": "category", "type": "text", "source": "payload.category"},
            {"name": "event_type", "type": "text", "source": "payload.type"},
            {"name": "result", "type": "text", "source": "payload.result"},
            # Stored for the raw table (a forensic question is asked of raw, over
            # a bounded window), NOT a dimension and NOT in the rollup: it is
            # per-person and high-cardinality.
            {"name": "cardholder_ref", "type": "text", "source": "payload.cardholder_ref"},
        ],
        "indexes": [
            {"name": "ix_access_events_tenant_ts", "columns": ["tenant_id", "ts"]},
            {"name": "ix_access_events_door_ts", "columns": ["door_id", "ts"]},
        ],
    },
    # Volume warrants exactly one rollup here. A door produces events at human
    # rates, not sensor rates, so an hourly bucket makes a month-wide chart cheap
    # and a second, finer rollup would earn nothing. The raw table answers
    # anything inside 48 hours and REFUSES a wider window by name (contract §4).
    "rollups": [
        {
            "key": "1h",
            "relation": "access_events_1h",
            "bucket": "1 hour",
            "time_column": "bucket",
            # Every registered dimension is a GROUP BY column, because the
            # registry has one dimension list for all relations: a dimension the
            # rollup did not carry would generate SQL naming a column that does
            # not exist there.
            "group_by": [
                "tenant_id", "door_id", "door_name", "result",
                "category", "event_type", "site_id", "instance_id",
            ],
            "aggregates": [{"name": "event_count", "fn": "count_star"}],
            # Real-time aggregate: the materialised part UNIONed with a live read
            # of the newest rows, so the CURRENT hour is present instead of a hole.
            "real_time": True,
            "refresh": {"start_offset": "7 days", "end_offset": "1 hour",
                        "schedule_interval": "5 minutes"},
            "retention": "1825 days",
        }
    ],
    # The `dashboard_datasets` row the projector publishes once the relations
    # above exist. Same shape, same validator, same executor as `iot_readings`.
    "dataset": {
        "name": "Door access events",
        "description": (
            "Controller events ingested by the access-control service: grants, "
            "denials, alarms and technical events, per door. Charts read the "
            "1-hour rollup; raw is available inside a 48-hour window."
        ),
        "permission": "access.events.read",
        "permission_label": "View door access events in dashboards",
        "permission_group": "Access control",
        "definition": {
            "tenant_column": "tenant_id",
            "relations": [
                {
                    "key": "raw",
                    "relation": "access_events",
                    "time_column": "ts",
                    "grain_sec": 0,
                    "max_window_minutes": 2880,
                    "reason": "raw access events (bounded 48-hour window) — every event, no aggregation",
                },
                {
                    "key": "1h",
                    "relation": "access_events_1h",
                    "time_column": "bucket",
                    "grain_sec": 3600,
                    "reason": (
                        "1-hour rollup (access_events_1h); real-time aggregate, "
                        "current hour included"
                    ),
                },
            ],
            "auto": [{"max_hours": 6, "relation": "raw"}, {"relation": "1h"}],
            "joins": [],
            "dimensions": [
                {"key": "door_id", "label": "Door", "source": "base", "column": "door_id", "type": "text"},
                {"key": "door_name", "label": "Door name", "source": "base", "column": "door_name", "type": "text"},
                {"key": "result", "label": "Result", "source": "base", "column": "result", "type": "text"},
                {"key": "category", "label": "Category", "source": "base", "column": "category", "type": "text"},
                {"key": "event_type", "label": "Event type", "source": "base", "column": "event_type", "type": "text"},
                {"key": "site_id", "label": "Site", "source": "base", "column": "site_id", "type": "text"},
                {"key": "instance_id", "label": "Controller", "source": "base", "column": "instance_id", "type": "text"},
            ],
            "measures": [
                {
                    "key": "events",
                    "label": "Events",
                    "type": "number",
                    "aggregates": ["sum"],
                    # A COUNT of events is comparable across doors, categories and
                    # controllers — unlike an IoT value, it is the same quantity
                    # everywhere and carries no unit to invent.
                    "comparable": True,
                    "physical": {
                        "raw": {"sum": {"fn": "count_star"}},
                        "1h": {"sum": {"fn": "sum", "column": "event_count"}},
                    },
                },
                {
                    "key": "doors",
                    "label": "Distinct doors",
                    "type": "number",
                    "aggregates": ["count_distinct"],
                    "comparable": True,
                    # Correct on the rollup too, and only because `door_id` is one
                    # of its GROUP BY columns: counting distinct values of a group
                    # key over rollup rows is the same set as over raw rows.
                    "physical": {
                        "raw": {"count_distinct": {"fn": "count_distinct", "column": "door_id"}},
                        "1h": {"count_distinct": {"fn": "count_distinct", "column": "door_id"}},
                    },
                },
            ],
            "defaults": {
                "series_by": "door_id",
                "label_dimension": "door_name",
                "measure": "events",
                "aggregate": "sum",
            },
        },
    },
}


def upgrade() -> None:
    op.create_table(
        "reporting_projections",
        sa.Column("key", sa.String(64), primary_key=True),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        # The whole recipe: source subject, target relation + columns, rollups,
        # and the dataset row to publish. Validated on load — a spec that does not
        # parse is SKIPPED with a logged reason, never half-applied.
        sa.Column("spec", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )

    # ── the synthetic fixture goes ───────────────────────────────────────────
    # It was created out of band (no migration ever declared it), so this drops
    # it defensively. The projector recreates all three for real.
    op.execute(sa.text("DELETE FROM dashboard_datasets WHERE key = 'access_events'"))
    op.execute(sa.text("DROP VIEW IF EXISTS access_events_1h"))
    op.execute(sa.text("DROP MATERIALIZED VIEW IF EXISTS access_events_1h"))
    op.execute(sa.text("DROP TABLE IF EXISTS access_events"))

    op.execute(
        sa.text(
            """
            INSERT INTO reporting_projections (key, name, description, enabled, spec)
            VALUES ('access_events',
                    'Access control events',
                    'Door/controller events published by the access service on '
                    'tenant.*.access.>, projected into a hypertable plus an hourly rollup.',
                    true,
                    CAST(:spec AS jsonb))
            """
        ).bindparams(spec=json.dumps(ACCESS_SPEC))
    )


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM dashboard_datasets WHERE key = 'access_events'"))
    op.drop_table("reporting_projections")
