"""Whether the Celery worker is still executing tasks, and whether beat is still sending them.

THE STATE THIS EXISTS TO MAKE VISIBLE. A Celery worker has a failure mode with no
outward symptom at all: the process is up, the broker connection is established,
``celery inspect ping`` answers ``pong``, the logs are quiet — and not one task is
being executed. It happens when the queue consumer is cancelled, when the prefork
pool deadlocks, when a reconnect re-registers the control queue but not the task
queue. ``inspect ping`` is answered by the CONTROL consumer on a broadcast queue,
which is a different consumer on a different queue from the one that carries work,
so it is structurally incapable of noticing. That is why this file exists instead
of a healthcheck that shells out to ``celery inspect ping``.

"NO WORK TO DO" IS NOT "NOT WORKING", AND THIS MUST NOT CONFLATE THEM. Workflow's
queue is idle most of the time: an estate can go a week without an incident, and a
liveness flag that reds on a quiet hour gets switched off within the week, taking
the real signal with it.

What makes the worker measurable anyway is that its queue is never actually empty.
``app.worker``'s beat schedule publishes ``escalation_sweep`` and
``dispatch_notifications`` on ``crontab(minute="*")`` — two tasks EVERY MINUTE,
forever, whether or not a single incident exists. A sweep that matches nothing
still connects, still opens a session, still queries, still returns. So:

    CONSUMING  ==  at least one Celery task has RUN TO COMPLETION within
                   VE_WORKFLOW_WORKER_SILENCE_SEC.

That is a heartbeat generated by the system's own clockwork rather than by
operator traffic, which is exactly what "idle must stay green" requires. It is
also a whole-chain proof: broker reachable, queue consumed, pool alive, task body
executed. A sweep returning 0 is the green signal, not a null result.

THE WINDOW: 300 seconds, five beat ticks. One missed tick is ordinary — beat
restarting, a sweep running long, a task landing either side of a minute
boundary. Five consecutive minutes with nothing completed is not something a
working worker does. Lower would flap on a container restart; much higher and a
wedge sits unreported through a shift change.

TWO ROLES, BECAUSE ONE NUMBER NAMES THE WRONG CONTAINER. If beat dies, the worker
completes nothing and its own silence would accuse a perfectly healthy worker. So
beat keeps its own heartbeat from ``before_task_publish``, and the worker's
readiness reason quotes BOTH ages: beat fresh + worker silent is a wedged worker;
both silent is a dead beat (or a dead broker), and the reason string says which.

WHY THE STATE LIVES IN REDIS AND NOT IN THE PROCESS. Two independent reasons, and
the first one is not obvious:

  * CELERY'S DEFAULT POOL IS PREFORK. ``task_postrun`` fires in a forked CHILD,
    not in MainProcess, and the children were forked before the probe server
    existed. An in-process counter is therefore invisible to the thread that
    serves ``/readyz`` and is separately wrong in each of the eleven children.
    This was written that way first and the probe sat at "no task ever completed"
    while the log showed tasks succeeding once a second. Redis is where the
    children and the parent can actually meet, and HINCRBY makes the counters
    correct across all of them without a lock.
  * The other reader is the API, in a different container. The broker they already
    share is the natural rendezvous, and it has a property a file or a pipe cannot
    have: if Redis is gone the heartbeat can be neither written nor read, which is
    the correct answer, because a worker that cannot reach its broker is a worker
    that is not consuming. The failure of the transport IS the signal — and the
    reader distinguishes "Redis unreachable" from "no heartbeat" so the reason
    string can say which.

Keys are ``neubit:workflow:health:*`` — this service's own prefix on a Redis
shared with core, ingest and the gateway — and carry a TTL, so a removed
deployment leaves nothing behind.
"""

from __future__ import annotations

import logging
import os
import time

from kernel.config import get_settings

log = logging.getLogger("workflow.runtime.heartbeat")

KEY_PREFIX = "neubit:workflow:health:"
# Long enough that an operator looking after an outage still sees the last thing
# the process managed to say; short enough that a decommissioned service does not
# leave a key behind forever. The silence limit reds long before this expires.
KEY_TTL_SEC = 3600


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return float(raw.strip())
    except ValueError:
        log.warning("%s=%r is not a number — using %s", name, raw, default)
        return default


# Five beat ticks. See the module docstring for why five and not one.
WORKER_SILENCE_SEC = _env_float("VE_WORKFLOW_WORKER_SILENCE_SEC", 300.0)
# Beat's own limit. Same reasoning, same clockwork: beat publishes twice a minute.
BEAT_SILENCE_SEC = _env_float("VE_WORKFLOW_BEAT_SILENCE_SEC", 300.0)


def key(role: str) -> str:
    return f"{KEY_PREFIX}{role}"


# ── writer side (worker / beat processes, including forked children) ─────────

_client = None


def _sync_client():
    global _client
    if _client is None:
        import redis  # celery's own dependency; already installed

        _client = redis.Redis.from_url(
            get_settings().redis_url,
            socket_connect_timeout=2, socket_timeout=2, decode_responses=True,
        )
    return _client


def arm(role: str) -> None:
    """Start this role's heartbeat fresh. Called once, in MainProcess, at boot.

    Deletes first so the counters mean "since this process started" rather than
    accumulating across restarts — a tasks_total that survives a crash makes a
    worker that has done nothing since rebooting look busy.
    """
    try:
        c = _sync_client()
        pipe = c.pipeline()
        pipe.delete(key(role))
        pipe.hset(key(role), mapping={"armed_at": repr(time.time()), "role": role})
        pipe.expire(key(role), KEY_TTL_SEC)
        pipe.execute()
    except Exception as e:  # noqa: BLE001
        log.warning("heartbeat arm failed for %s: %s", role, e)


def note(role: str, name: str, *, failed: bool = False) -> None:
    """Record that this role just did its thing. Never raises.

    Called from a Celery signal, i.e. on the path of every task, so it must not be
    able to fail a task: a liveness signal that can take down the thing it watches
    is worse than no liveness signal. A write that fails is also self-reporting —
    the field goes stale and the reader draws the correct conclusion.

    HINCRBY rather than a read-modify-write because eleven prefork children stamp
    this concurrently; the server-side increment is what makes the count right
    without any of them holding a lock.
    """
    try:
        c = _sync_client()
        pipe = c.pipeline()
        pipe.hset(key(role), mapping={
            "last_event_at": repr(time.time()), "last_event_name": name[:200],
        })
        pipe.hincrby(key(role), "events_total", 1)
        if failed:
            pipe.hincrby(key(role), "failures_total", 1)
            pipe.hset(key(role), "last_error", name[:300])
        pipe.expire(key(role), KEY_TTL_SEC)
        pipe.execute()
    except Exception as e:  # noqa: BLE001
        log.warning("heartbeat note failed for %s: %s", role, e)


# ── reader side ──────────────────────────────────────────────────────────────


def _parse(raw: dict | None) -> dict | None:
    if not raw:
        return None
    def f(k):
        try:
            return float(raw[k])
        except (KeyError, TypeError, ValueError):
            return None
    return {
        "role": raw.get("role"),
        "armed_at": f("armed_at"),
        "last_event_at": f("last_event_at"),
        "last_event_name": raw.get("last_event_name"),
        "events_total": int(raw.get("events_total") or 0),
        "failures_total": int(raw.get("failures_total") or 0),
        "last_error": raw.get("last_error"),
    }


def read_sync(role: str) -> tuple[dict | None, str | None]:
    """(payload, error). Used by the worker's own probe thread — no event loop there.

    The error is returned rather than folded into ``payload is None`` because
    "Redis is unreachable" and "this role has never published" send an operator to
    two entirely different places, and a probe that says only "unknown" sends them
    to neither.
    """
    try:
        return _parse(_sync_client().hgetall(key(role))), None
    except Exception as e:  # noqa: BLE001
        return None, f"{type(e).__name__}: {e}"[:200]


_aclient = None


async def read(role: str) -> tuple[dict | None, str | None]:
    """Async twin of :func:`read_sync`, for the API process."""
    global _aclient
    try:
        if _aclient is None:
            import redis.asyncio as aredis

            _aclient = aredis.Redis.from_url(
                get_settings().redis_url,
                socket_connect_timeout=2, socket_timeout=2, decode_responses=True,
            )
        return _parse(await _aclient.hgetall(key(role))), None
    except Exception as e:  # noqa: BLE001
        return None, f"{type(e).__name__}: {e}"[:200]


def age_of(payload: dict | None) -> float | None:
    """Seconds since that role last did its thing. None = nothing to go on.

    Falls back to ``armed_at`` when no event has been recorded yet, which is what
    gives a freshly booted worker its grace period instead of reporting an
    infinite silence during the first minute of its life, before anything has had
    a chance to be scheduled.
    """
    if not payload:
        return None
    when = payload.get("last_event_at") or payload.get("armed_at")
    return None if not when else round(time.time() - float(when), 1)


async def close_reader() -> None:
    global _aclient
    if _aclient is not None:
        try:
            await _aclient.aclose()
        except Exception:  # noqa: BLE001
            pass
        _aclient = None
