"""Alembic environment (async) for the reporting store.

Same shape as the other services' migrations/env.py: the DB URL comes from
VE_DATABASE_URL (via kernel settings), not alembic.ini. Import every model module
below so ``Base.metadata`` is complete.

NOTE on autogenerate: `readings` is a TimescaleDB HYPERTABLE and the 1m/1h
rollups are CONTINUOUS AGGREGATES. Neither is expressible in SQLAlchemy metadata,
and Timescale's internal schemas (`_timescaledb_internal`, `_timescaledb_catalog`)
are full of tables the ORM knows nothing about. ``include_object`` below keeps
autogenerate away from all of it — without it, an autogenerated revision would
cheerfully propose dropping every chunk in the database.
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from kernel.config import get_settings

from reporting.db import Base

# Import all model modules so their tables register on Base.metadata.
import reporting.models  # noqa: E402,F401  (Point + Reading)

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)
target_metadata = Base.metadata

# Everything TimescaleDB owns, plus the materialised views it creates for the
# continuous aggregates, is invisible to autogenerate.
_TIMESCALE_SCHEMAS = {
    "_timescaledb_internal",
    "_timescaledb_catalog",
    "_timescaledb_config",
    "_timescaledb_cache",
    "timescaledb_information",
    "timescaledb_experimental",
}
_MANAGED_VIEWS = {"readings_1m", "readings_1h"}


def include_object(obj, name, type_, reflected, compare_to):
    if getattr(obj, "schema", None) in _TIMESCALE_SCHEMAS:
        return False
    # `readings_1m` / `readings_1h` are continuous aggregates, not ORM tables.
    return not (type_ == "table" and name in _MANAGED_VIEWS)


def do_run_migrations(connection):
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        include_schemas=False,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_online():
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_offline():
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        include_object=include_object,
        literal_binds=True,
    )
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_offline()
else:
    asyncio.run(run_online())
