"""Alembic environment (async) for the reporting store.

Same shape as the other services' migrations/env.py: the DB URL comes from
VE_DATABASE_URL (via kernel settings), not alembic.ini. Import every model module
below so ``Base.metadata`` is complete.

NOTE on autogenerate: `readings` is a TimescaleDB HYPERTABLE and the 1m/1h
rollups are CONTINUOUS AGGREGATES. Neither is expressible in SQLAlchemy metadata,
and Timescale's internal schemas (`_timescaledb_internal`, `_timescaledb_catalog`)
are full of tables the ORM knows nothing about. ``include_object`` below keeps
autogenerate away from all of it — without it, an autogenerated revision would
cheerfully propose dropping every chunk in the database.

The same rule covers the PROJECTION relations. A row in `reporting_projections`
creates its own table and rollups at runtime (reading-writer's
app/projections/ensure.py), on purpose: a projection is inserted as data, with no
deploy, so no migration can declare its relations ahead of time. Autogenerate
sees tables nothing accounts for and proposes DROP TABLE on live telemetry. The
names are therefore read back OUT of the registry rather than listed here — a
hardcoded list would be wrong the first time somebody adds a projection.
"""

import asyncio
import json
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool, text
from sqlalchemy.ext.asyncio import async_engine_from_config

from kernel.config import get_settings

from reporting.db import Base

# Import all model modules so their tables register on Base.metadata.
import reporting.models  # noqa: E402,F401  (Point + Reading)

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)
target_metadata = Base.metadata

# Everything TimescaleDB owns, plus the materialised views it creates for the
# continuous aggregates, is invisible to autogenerate.
_TIMESCALE_SCHEMAS = {
    "_timescaledb_internal",
    "_timescaledb_catalog",
    "_timescaledb_config",
    "_timescaledb_cache",
    "timescaledb_information",
    "timescaledb_experimental",
}
_MANAGED_VIEWS = {"readings_1m", "readings_1h"}

# create_hypertable() adds its own index on the time column and names it
# `<relation>_<time column>_idx`. It is not ours and no migration wrote it, so
# autogenerate must not offer to drop it. Only `readings` needs naming: the
# projection hypertables are skipped whole, indexes included.
_TIMESCALE_TIME_INDEXES = {"readings_ts_idx"}


def projection_relations(connection) -> set[str]:
    """Relations the projection registry owns — read from the registry itself.

    Empty before migration 0005 creates the registry, which is the state a fresh
    database migrates through. Reads every row, not just the enabled ones: a
    disabled projection stops consuming, but its table stays right where it is.
    """
    if connection.execute(
        text("SELECT to_regclass('public.reporting_projections')")
    ).scalar() is None:
        return set()
    names: set[str] = set()
    for (spec,) in connection.execute(text("SELECT spec FROM reporting_projections")):
        if isinstance(spec, (str, bytes)):
            spec = json.loads(spec)
        if not isinstance(spec, dict):
            continue
        target = spec.get("target")
        if isinstance(target, dict) and target.get("relation"):
            names.add(str(target["relation"]))
        for rollup in spec.get("rollups") or []:
            if isinstance(rollup, dict) and rollup.get("relation"):
                names.add(str(rollup["relation"]))
    return names


def make_include_object(projected: set[str]):
    """The autogenerate filter. `projected` is empty offline, where there is no
    connection to ask."""

    def include_object(obj, name, type_, reflected, compare_to):
        if getattr(obj, "schema", None) in _TIMESCALE_SCHEMAS:
            return False
        if type_ == "table" and (name in _MANAGED_VIEWS or name in projected):
            return False
        return not (type_ == "index" and name in _TIMESCALE_TIME_INDEXES)

    return include_object


def do_run_migrations(connection):
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=make_include_object(projection_relations(connection)),
        include_schemas=False,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_online():
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
        # COMMIT EXPLICITLY. Without this every migration is a silent no-op:
        # alembic logs "Running upgrade X -> Y", the process exits 0, and
        # `alembic current` still reports X.
        #
        # Why it happens. SQLAlchemy 2.0 opens an implicit transaction on the
        # first execute, so by the time alembic's MigrationContext looks at the
        # connection it is ALREADY in one. Alembic reads that as "the caller is
        # managing transactions" and declines to commit — correctly, because
        # committing someone else's transaction would be worse. Nobody then
        # does, and `async with connectable.connect()` rolls back on exit.
        #
        # Measured, not reasoned: an empty migration whose upgrade() was `pass`
        # printed "Running upgrade 0020 -> 0022", exited 0, and left
        # alembic_version at 0020.
        #
        # Safe when alembic DID commit: Connection.commit() with no transaction
        # open is a no-op in SQLAlchemy 2.0.
        await connection.commit()
    await connectable.dispose()


def run_offline():
    context.configure(
        url=get_settings().database_url,
        target_metadata=target_metadata,
        include_object=make_include_object(set()),
        literal_binds=True,
    )
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_offline()
else:
    asyncio.run(run_online())
